Models/PoorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Gam3iaWeb.Models
{
    public class PoorViewModel
    {
        Gam3iaEntities context = new Gam3iaEntities();
        [Key]
        public int ID { get; set; }
        [Display(Name = "رقم بطاقة الحاله")]
        public string PoorNID { get; set; }
        [Display(Name = "اسم الحاله")]
        public string PoorName { get; set; }
        [Display(Name = "تاريخ تسجيل الحاله")]
        [DataType(DataType.Date)]
        public Nullable<DateTime>RegisterDate { get; set; }
        [Display(Name = "البلد")]
        public Nullable<int> CityID { get; set; }
        [Display(Name = "البلد")]
        public string CityName { get; set; }


        public static implicit operator PoorViewModel(Poor poor)
        {
            return new PoorViewModel()
            {
                ID = poor.ID,
                PoorName = poor.PoorName,
                PoorNID = poor.PoorNID,
                RegisterDate=poor.RegisterDate,
                CityID=poor.City.ID,
                CityName=poor.City.CityName
            };

        }

        public static implicit operator Poor(PoorViewModel vm)
        {
            return new Poor()
            {
                ID = vm.ID,
                PoorName = vm.PoorName,
                PoorNID = vm.PoorNID,
                RegisterDate=vm.RegisterDate,
                CityID=vm.CityID
            };
        }

        }
}

Controllers/PoorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gam3iaWeb;
using Gam3iaWeb.Models;

namespace Gam3iaWeb.Controllers
{
    [Authorize]
    public class PoorsController : Controller
    {
        private Gam3iaEntities db = new Gam3iaEntities();

        // GET: Poors
        public ActionResult Index(string searchby,string search)
        {
            List<Poor> ps = db.Poor.ToList();
            if (searchby == "PoorName")
            {
                ps=db.Poor.Where(x => x.PoorName.Contains( search )).ToList();
            }
            if (searchby == "PoorNID")
            {
                ps=db.Poor.Where(x => x.PoorNID.Equals(search)).ToList();
            }
            
            List<PoorViewModel> poorsvm = new List<PoorViewModel>();
           
            foreach (Poor item in ps)
            {
                poorsvm.Add((PoorViewModel)item);

            }
            return View(poorsvm);
        }
        // GET: GetCaseStudies/1
        public ActionResult GetCaseStudies(int? poorid)
        {

            if (poorid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Poor po = (from p in db.Poor where p.ID == poorid select p).FirstOrDefault();

                List<CaseStudyViewModel> cslst = new List<CaseStudyViewModel>();

                var case_studies = (from i in db.CaseStudy where i.PoorID == poorid select i).ToList();
                if (case_studies.Count == 0)
                    ViewBag.RelatedCaseStudyMsg = "لا  توجد أبحاث حاله متعلقه بهذا العنصر..";
                else
                {
                    foreach (var item in case_studies)
                    {
                        cslst.Add((CaseStudyViewModel)item);
                    }
                }


                return View(cslst);
            }
        }

        public ActionResult GetPoorHistory(int? poorid)
        {

            if (poorid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                Poor po = (from p in db.Poor where p.ID == poorid select p).FirstOrDefault();


                List<Loan> lolst = (from i in db.Loan where i.PoorID == poorid select i).ToList();
                if (lolst.Count == 0)
                    ViewBag.RelatedLoanMsg = "لا  توجد قروض متعلقه بهذا العنصر..";
                else
                {
                    ViewBag.LoanList = lolst;
                }
                List<StudentAid> sdonationlst = (from i in db.StudentAid where i.PoorID == poorid select i).ToList();
                if (sdonationlst.Count == 0)
                    ViewBag.RelatedStudentAidMsg = "لا  توجد مساعدات طالب متعلقه بهذا العنصر..";
                else
                {
                    ViewBag.StudentAidList = sdonationlst;
                }
                List<PhysicalDonation> donationlst = (from i in db.PhysicalDonation where i.PoorID == poorid select i).ToList();
                if (donationlst.Count == 0)
                    ViewBag.RelatedPhysicalDonationMsg = "لا  توجد تبرعات عينيه مستلمه متعلقه بهذا العنصر..";
                else
                {
                    ViewBag.PhysicalDonationList = donationlst;
                }


                return View();
            }
        }

        // GET: Poors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poor poor = db.Poor.Find(id);
            if (poor == null)
            {
                return HttpNotFound();
            }
           
            return View((PoorViewModel)poor);
        }

        // GET: Poors/Create
        public ActionResult Create()
        {
            ViewBag.CityID = new SelectList(db.City, "ID", "CityName");

            return View();

        }

        // POST: Poors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PoorNID,PoorName,RegisterDate,CityID")] PoorViewModel poorvm)
        {
            Poor poor = (Poor)poorvm;
            if (ModelState.IsValid)
            {
                
                db.Poor.Add(poor);
                db.SaveChanges();
                if (Session["caller"] != null)
                {
                    if (Session["caller"].ToString() == "CaseStudy")
                    {
                        Session["caller"] = "";
                        return RedirectToAction("Create", "CaseStudies");

                    }
                    if (Session["caller"].ToString() == "Loan")
                    {
                        Session["caller"] = "";
                        return RedirectToAction("Create", "Loans");

                    }
                    if (Session["caller"].ToString() == "StudentAid")
                    {
                        Session["caller"] = "";
                        return RedirectToAction("Create", "StudentAids");

                    }
                    if (Session["caller"].ToString() == "GeneralAid")
                    {
                        Session["caller"] = "";
                        return RedirectToAction("Create", "GeneralAids");

                    }
                }
                else
                    return RedirectToAction("Index");


            }

            return View((PoorViewModel)poor);
        }

        // GET: Poors/Edit/5
        public ActionResult Edit(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poor poor = db.Poor.Find(id);
            if (poor == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.City, "ID", "CityName",poor.CityID);

            return View((PoorViewModel)poor);
        }

        // POST: Poors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PoorNID,PoorName,CityID")] PoorViewModel poorvm)
        {
            Poor poor = (Poor)poorvm;
            if (ModelState.IsValid)
            {
                db.Entry(poor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View((PoorViewModel)poor);
        }

        // GET: Poors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poor poor = db.Poor.Find(id);
            if (poor == null)
            {
                return HttpNotFound();
            }
            return View((PoorViewModel)poor);
        }

        // POST: Poors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Poor poor = db.Poor.Find(id);
            db.Poor.Remove(poor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Poors/Create.cshtml
@model Gam3iaWeb.Models.PoorViewModel

@{
    ViewBag.Title = "إضافة محتاج";
}
<div class="container">
    <h2>إضافة محتاج</h2>
    @if (Session["caller"]!=null&&Session["caller"].ToString() == "CaseStudy")
    {
        <p class="label-info">من فضلك املأ بيانات المحتاج أولا قبل بحث الحاله</p>
    }
    @if (Session["caller"] != null && Session["caller"].ToString() == "Loan")
    {
        <p class="label-info">من فضلك املأ بيانات المحتاج أولا قبل إضافة القرض الحسن</p>
    }
    @if (Session["caller"] != null && Session["caller"].ToString() == "StudentAid")
    {
        <p class="label-info">من فضلك املأ بيانات الطالب أولا قبل ملء بيانات المساعدة</p>
    }
    @if (Session["caller"] != null && Session["caller"].ToString() == "GeneralAid")
    {
        <p class="label-info">من فضلك املأ بيانات الحاله أولا قبل ملء بيانات المساعدة</p>
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.PoorNID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5 col-md-offset-1">
                    @Html.EditorFor(model => model.PoorNID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PoorNID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PoorName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5 col-md-offset-1">
                    @Html.EditorFor(model => model.PoorName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PoorName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.RegisterDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5 col-md-offset-1">
                    @Html.EditorFor(model => model.RegisterDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RegisterDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CityID, "البلد", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5 col-md-offset-1">
                    @Html.DropDownList("CityID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-5 col-md-offset-1">
                    <input type="submit" value="إضافة" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("عودة إلي قائمة الحالات", "Index")
    </div>
</div>

Views/Poors/Delete.cshtml
@model Gam3iaWeb.Models.PoorViewModel

@{
    ViewBag.Title = "حذف";
}

<h2>Delete</h2>

<h3>هل أنت متأكد من حذف بيانات هذا العنصر؟?</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PoorNID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoorNID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PoorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoorName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="مسح" class="btn btn-default" /> |
            @Html.ActionLink("عودة إلي القائمة", "Index")
        </div>
    }
</div>

Views/Poors/Details.cshtml
@model Gam3iaWeb.Models.PoorViewModel

@{
    ViewBag.Title = "تفاصيل البيانات";
}

<h2>تفاصيل البيانات</h2>

<div >
    <p class="float_left">
        @Html.ActionLink("تعديل", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("عودة إلي القائمة", "Index")
    </p>
    <hr />
    <div class="form-horizontal disabledform">

       

        <div class="form-group">
            @Html.LabelFor(model => model.PoorNID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.PoorNID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PoorNID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PoorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.PoorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PoorName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CityID, "البلد", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>
       
    </div>
</div>



@*<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">
                ممتلكات الأسره
            </a>
        </h4>
    </div>
    <div id="collapse4" class="panel-collapse collapse">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    

                    

                    
                </div>
                <div class="col-md-6">
                   
                   
                </div>
            </div>
        </div>
    </div>
</div>*@

Views/Poors/Edit.cshtml
@model Gam3iaWeb.Models.PoorViewModel

@{
    ViewBag.Title = "تعديل";
}

<h2>تعديل</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PoorNID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.PoorNID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PoorNID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PoorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.PoorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PoorName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CityID, "البلد", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.DropDownList("CityID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-5 col-md-offset-1">
                <input type="submit" value="حفظ" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("عودة إلي القائمة", "Index")
</div>

Views/Poors/GetCaseStudies.cshtml
@model IEnumerable<Gam3iaWeb.Models.CaseStudyViewModel>

@{
    ViewBag.Title = "قائمة الأقساط";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2> قائمة  أبحاث الحاله المتعلقه بالعنصر</h2>

<p class="float_left">

    @Html.ActionLink("عودة إلي القائمة", "Index")
</p>
<br />

@if (ViewBag.RelatedCaseStudyMsg != null)
{
    <p class="label-info">
        @ViewBag.RelatedCaseStudyMsg
    </p>

}

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.VillageName)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.ReporterName)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.ReporterPhone)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.FamilyClass)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.PoorName)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.PoorNID)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.PartnerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PartnerNID)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Breadwinner)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Job)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.EducationState)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.ChildrenNo)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.ChildrenInEducationNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TravelledOrMarriedChildrenNo)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Telephone1)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Telephone2)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Target)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.ReviewerOpinion)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.VolunteerName)
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VillageName)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.ReporterName)
                </td>*@
            @*<td>
                    @Html.DisplayFor(modelItem => item.ReporterPhone)
                </td>*@
            @*<td>
                    @Html.DisplayFor(modelItem => item.FamilyClass)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.PoorName)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.PoorNID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PartnerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PartnerNID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Breadwinner)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Job)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.EducationState)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.ChildrenNo)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.ChildrenInEducationNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TravelledOrMarriedChildrenNo)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Telephone1)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Telephone2)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Target)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.ReviewerOpinion)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.VolunteerName)
            </td>
           
            <td>
                @*@Html.ActionLink("تعديل", "Edit","CaseStudies", new { id = item.CaseID },null) |*@
                @Html.ActionLink("التفاصيل", "Details", "CaseStudies", new { id = item.CaseID },null) |
                @Html.ActionLink("مسح", "Delete", "CaseStudies", new { id = item.CaseID },null)
            </td>
        </tr>
    }

</table>

Views/Poors/GetPoorHistory.cshtml
@{
    ViewBag.Title = "GetPoorHistory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>عرض تاريخ الحاله</h2>
@if (ViewBag.RelatedLoanMsg != null)
{
<h3>
    @ViewBag.RelatedLoanMsg
</h3>
}
else
{
    <h3> القروض</h3>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                
                <th>
                   اسم المقترض
                </th>
                <th>
                 العنوان
                </th>
                <th>
                   التليفون
                </th>


               
                <th>
                  قيمة القرض
                </th>
                <th>
                   الأقساط المدفوعه
                </th>
              
                <th>
                   اسم المتطوع
                </th>
                @*<th>
                        @Html.DisplayNameFor(model => model.PoorName)
                    </th>*@
                <th></th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in ViewBag.LoanList)
        {
            <tr>
               
                <td>
                   @item.Poor.PoorName
                </td>
                <td>
                    @item.Address
                </td>
                <td>
                    @item.Telephone1
                </td>

               

                <td>
                    @item.LoanValue
                </td>
                <td>
                    @item.PaidInstallments
                </td>
             
                <td>
                    @item.AspNetUsers.UserName
                </td>
                <td>
                    @Html.ActionLink("عرض الأقساط", "GetInstallments", "Loans", new { loanid = item.ID }, null)
                </td>
                <td>
                    @Html.ActionLink("تعديل", "Edit","Loans", new { id = item.ID },null) |
                    @Html.ActionLink("تفاصيل", "Details", "Loans", new { id = item.ID },null) |
                    @Html.ActionLink("مسح", "Delete", "Loans", new { id = item.ID },null)
                </td>
            </tr>
        }

    </table>

}
<h3>
    @ViewBag.RelatedStudentAidMsg
</h3>
<h3>
    @ViewBag.RelatedPhysicalDonationMsg
</h3>

Views/Poors/Index.cshtml
@model IEnumerable<Gam3iaWeb.Models.PoorViewModel>

@{
    ViewBag.Title = "جميع الحالات ";
}

<div class="container">
    <h2>جميع الحالات</h2>
    @using (Html.BeginForm("Index", "Poors", FormMethod.Get))
    {
        <b>بحث بـ :</b>@Html.RadioButton("searchBy", "PoorName", true)<text> اسم الحاله</text>
        @Html.RadioButton("searchBy", "PoorNID")<text>الرقم القومي</text><br />
        @Html.TextBox("Search");<input type="submit" value="بحث" />
    }
    <p class="float_left">
        @Html.ActionLink("إضافة محتاج", "Create" ,null, new { @class = "btn btn-default", @role = "button" })
    </p>
    <br/>
    @*<a href="javascript:window.print()">Click to Print This Page</a>*@
    <table class="table table-hover table-striped datatable_nosearch">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PoorNID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PoorName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CityID)
                </th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PoorNID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PoorName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CityName)
                    </td>
                    <td>
                        @Html.ActionLink("مساعدات سابقة ", "GetPoorHistory", new { poorid = item.ID })
                    </td>
                    <td>
                        @Html.ActionLink("عرض أبحاث الحاله ", "GetCaseStudies", new { poorid = item.ID })
                    </td>
                    <td>
                        @Html.ActionLink("تعديل", "Edit", new { id = item.ID }) |
                        @Html.ActionLink("التفاصيل", "Details", new { id = item.ID }) |
                        @Html.ActionLink("حذف", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

</table>
</div>