Controllers/PhysicalDonationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

using Gam3iaWeb;

namespace Gam3iaWeb.Controllers
{
    public class PhysicalDonationsController : Controller
    {
        private Gam3iaEntities db = new Gam3iaEntities();

        // GET: PhysicalDonations
        public ActionResult Index()
        {
            var physicalDonation = db.PhysicalDonation.Include(p => p.AspNetUsers).Include(p => p.Donator).Include(p => p.Poor);
            return View(physicalDonation.ToList());
        }

        // GET: PhysicalDonations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhysicalDonation physicalDonation = db.PhysicalDonation.Find(id);
            if (physicalDonation == null)
            {
                return HttpNotFound();
            }
            return View(physicalDonation);
        }

        // GET: PhysicalDonations/Create
        public ActionResult Create()
        {
            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName");
            ViewBag.DonatorID = new SelectList(db.Donator, "ID", "DonatorName");
            List<Poor> plist = db.Poor.ToList();
            plist.Insert(0, new Poor() { ID = 0, PoorName = "غير محدد" });
            ViewBag.PoorID = new SelectList(plist, "ID", "PoorName");
            return View();
        }

        // POST: PhysicalDonations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        // GET: PhysicalDonations/CreateNew
        public ActionResult CreateNew()
        {
            Session["caller"] = "PDonations";
            return RedirectToAction("Create", "Donators");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,DonationType,DeviceName,DeviceState,CanBeFixed,FixFees,ReceiveDate,IsSelled,IsDelivered,SellPrice,SellDate,DonatorID,PoorID")] PhysicalDonation physicalDonation)
        {
            if (physicalDonation.PoorID == 0)
                physicalDonation.PoorID = null;
            if (ModelState.IsValid)
            {
                physicalDonation.VolunteerID = User.Identity.GetUserId();
                db.PhysicalDonation.Add(physicalDonation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName", physicalDonation.VolunteerID);
            ViewBag.DonatorID = new SelectList(db.Donator, "ID", "DonatorName", physicalDonation.DonatorID);
            List<Poor> plist = db.Poor.ToList();
            plist.Insert(0, new Poor() { ID = 0, PoorName = "غير محدد" });
            

            ViewBag.PoorID = new SelectList(plist, "ID", "PoorName", physicalDonation.PoorID);
            return View(physicalDonation);
        }

        // GET: PhysicalDonations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhysicalDonation physicalDonation = db.PhysicalDonation.Find(id);
            if (physicalDonation == null)
            {
                return HttpNotFound();
            }
            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName", physicalDonation.VolunteerID);
            ViewBag.DonatorID = new SelectList(db.Donator, "ID", "DonatorName", physicalDonation.DonatorID);
            List<Poor> plist = db.Poor.ToList();
            plist.Insert(0, new Poor() { ID = 0, PoorName = "غير محدد" });
            ViewBag.PoorID = new SelectList(plist, "ID", "PoorName", physicalDonation.PoorID);
            
            return View(physicalDonation);
        }

        // POST: PhysicalDonations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,DonationType,DeviceName,DeviceState,CanBeFixed,FixFees,ReceiveDate,IsSelled,IsDelivered,SellPrice,SellDate,DonatorID,PoorID")] PhysicalDonation physicalDonation)
        {
            if (physicalDonation.PoorID == 0)
                physicalDonation.PoorID = null;
            if (ModelState.IsValid)
            {
                db.Entry(physicalDonation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName", physicalDonation.VolunteerID);
            ViewBag.DonatorID = new SelectList(db.Donator, "ID", "DonatorName", physicalDonation.DonatorID);
            ViewBag.PoorID = new SelectList(db.Poor, "ID", "PoorName", physicalDonation.PoorID);
            return View(physicalDonation);
        }

        // GET: PhysicalDonations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhysicalDonation physicalDonation = db.PhysicalDonation.Find(id);
            if (physicalDonation == null)
            {
                return HttpNotFound();
            }
            return View(physicalDonation);
        }

        // POST: PhysicalDonations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhysicalDonation physicalDonation = db.PhysicalDonation.Find(id);
            db.PhysicalDonation.Remove(physicalDonation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/PhysicalDonations/Create.cshtml
@model Gam3iaWeb.PhysicalDonation

@{
    ViewBag.Title = "إنشاء تبرع عيني جديد";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>إنشاء تبرع عيني جديد</h2>
<div>
    @Html.ActionLink("عودة إلي  القائمة", "Index")
</div>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DonationType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.DonationType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonationType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.DeviceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceState, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.DeviceState, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceState, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CanBeFixed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2 col-md-offset-1">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CanBeFixedNotNull)
                    @Html.ValidationMessageFor(model => model.CanBeFixedNotNull, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FixFees, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.FixFees, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FixFees, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReceiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.ReceiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReceiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSelled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2 col-md-offset-1">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsSelledNotNull)
                    @Html.ValidationMessageFor(model => model.IsSelledNotNull, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDelivered, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2 col-md-offset-1">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeliveredNotNull)
                    @Html.ValidationMessageFor(model => model.IsDeliveredNotNull, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.SellPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.SellDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellDate, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.DonatorID, "اسم المتبرع", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.DropDownList("DonatorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DonatorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PoorID, "اسم الحاله (في حالة تسليم التبرع)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.DropDownList("PoorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PoorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5 col-md-offset-1">
                <input type="submit" value="إنشاء" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/PhysicalDonations/Delete.cshtml
@model Gam3iaWeb.PhysicalDonation

@{
    ViewBag.Title = "حذف";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>حذف</h2>

<h3>هل أنت واثق من حذف هذا العنصر؟</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DonationType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonationType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CanBeFixedNotNull)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CanBeFixedNotNull)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FixFees)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FixFees)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSelled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSelled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDelivered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDelivered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SellPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SellDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Donator.DonatorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Donator.DonatorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Poor.PoorNID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Poor.PoorNID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/PhysicalDonations/Details.cshtml
@model Gam3iaWeb.PhysicalDonation

@{
    ViewBag.Title = "تفاصيل التبرع";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>تفاصيل التبرع</h2>
<p class="float_left">
    @Html.ActionLink("تعديل", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("عودة إلي القائمة", "Index")
</p>
<div>
   
    <hr />
    <div class="form-horizontal disabledform">

       
        <div class="form-group">
            @Html.LabelFor(model => model.DonationType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.DonationType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonationType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.DeviceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceState, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.DeviceState, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceState, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CanBeFixedNotNull, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CanBeFixedNotNull)
                    @Html.ValidationMessageFor(model => model.CanBeFixed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FixFees, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.FixFees, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FixFees, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReceiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.ReceiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReceiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSelledNotNull, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsSelledNotNull)
                    @Html.ValidationMessageFor(model => model.IsSelled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDelivered, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeliveredNotNull)
                    @Html.ValidationMessageFor(model => model.IsDeliveredNotNull, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.SellPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.SellDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.DonatorID, "اسم المتبرع", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Donator.DonatorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonatorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PoorID, "اسم الحاله (في حالة تسليم التبرع)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Poor.PoorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PoorID, "", new { @class = "text-danger" })
            </div>
        </div>

       
    </div>
</div>

Views/PhysicalDonations/Index.cshtml
@model IEnumerable<Gam3iaWeb.PhysicalDonation>

@{
    ViewBag.Title = "قائمة التبرعات العينيه";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>قائمة التبرعات العينيه</h2>

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        @Html.ActionLink("تبرع من متبرع جديد", "CreateNew", "PhysicalDonations", null, new { @class = "btn btn-default", @role = "button" })
    </div>
    <div class="col-md-4"> @Html.ActionLink("تبرع من متبرع سابق", "Create", "PhysicalDonations", null, new { @class = "btn btn-default", @role = "button" })</div>

</div>
<br />

<table class="table table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DonationType)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.DeviceName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DeviceState)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CanBeFixed)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FixFees)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.ReceiveDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsSelledNotNull)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeliveredNotNull)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.SellPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SellDate)
                </th>*@
            
            <th>
                @Html.DisplayNameFor(model => model.DonatorID)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.PoorID)
                </th>*@
            <th></th>
        </tr>
    </thead>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DonationType)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.DeviceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DeviceState)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CanBeFixed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FixFees)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.ReceiveDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsSelled)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDelivered)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.SellPrice)
        </td>*@
        @*<td>
            @Html.DisplayFor(modelItem => item.SellDate)
        </td>*@
       
        <td>
            @Html.DisplayFor(modelItem => item.Donator.DonatorName)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Poor.PoorName)
        </td>*@
        <td>
            @Html.ActionLink("تعديل", "Edit", new { id=item.ID }) |
            @Html.ActionLink("التفاصيل", "Details", new { id=item.ID }) |
            @Html.ActionLink("حذف", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>