Controllers/GeneralAidsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Gam3iaWeb;

namespace Gam3iaWeb.Controllers
{
    [Authorize]
    public class GeneralAidsController : Controller
    {
        private Gam3iaEntities db = new Gam3iaEntities();
        
        // GET: GeneralAids
        public ActionResult Index( int serviceid=0)
        {
            List<Service> services = db.Service.ToList();
            services.Insert(0, new Service() { ServiceID = 0, ServiceName = "الكل" });
            ViewBag.ServicesList = new SelectList(services, "ServiceID", "ServiceName",serviceid);
           
            List<GeneralAid> generalAid = new List<GeneralAid>();
            if (serviceid == 0)
            {
                 generalAid = db.GeneralAid.Include(g => g.AspNetUsers).Include(g => g.Poor).Include(g => g.Service).ToList();
                //ViewBag.SelectedOption = serviceid;
            }
            else
            {
                 generalAid = db.GeneralAid.Where(g=>g.ServiceID==serviceid).Include(g => g.AspNetUsers).Include(g => g.Poor).Include(g => g.Service).ToList();

            }
            return View(generalAid);
        }

        // GET: GeneralAids/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GeneralAid generalAid = db.GeneralAid.Find(id);
            if (generalAid == null)
            {
                return HttpNotFound();
            }
            return View(generalAid);
        }

        // GET: GeneralAids/Create
        public ActionResult Create()
        {
            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName");
            ViewBag.PoorID = new SelectList(db.Poor, "ID", "PoorName");
            ViewBag.ServiceID = new SelectList(db.Service, "ServiceID", "ServiceName");
            return View();
        }

        // POST: GeneralAids/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Comment,Tag,PoorID,ServiceID,ReceiveDate,Value")] GeneralAid generalAid)
        {

            generalAid.VolunteerID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.GeneralAid.Add(generalAid);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName", generalAid.VolunteerID);
            ViewBag.PoorID = new SelectList(db.Poor, "ID", "PoorName", generalAid.PoorID);
            ViewBag.ServiceID = new SelectList(db.Service, "ServiceID", "ServiceName", generalAid.ServiceID);
            return View(generalAid);
        }

        public ActionResult CreateNew()
        {

            Session["caller"] = "GeneralAid";
            return RedirectToAction("Create", "Poors");
        }
        // GET: GeneralAids/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GeneralAid generalAid = db.GeneralAid.Find(id);
            if (generalAid == null)
            {
                return HttpNotFound();
            }
            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName", generalAid.VolunteerID);
            ViewBag.PoorID = new SelectList(db.Poor, "ID", "PoorName", generalAid.PoorID);
            ViewBag.ServiceID = new SelectList(db.Service, "ServiceID", "ServiceName", generalAid.ServiceID);
            return View(generalAid);
        }

        // POST: GeneralAids/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Comment,PoorID,ServiceID,ReceiveDate,Value")] GeneralAid generalAid)
        {
            if (ModelState.IsValid)
            {
                db.Entry(generalAid).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName", generalAid.VolunteerID);
            ViewBag.PoorID = new SelectList(db.Poor, "ID", "PoorName", generalAid.PoorID);
            ViewBag.ServiceID = new SelectList(db.Service, "ServiceID", "ServiceName", generalAid.ServiceID);
            return View(generalAid);
        }

        // GET: GeneralAids/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GeneralAid generalAid = db.GeneralAid.Find(id);
            if (generalAid == null)
            {
                return HttpNotFound();
            }
            return View(generalAid);
        }

        // POST: GeneralAids/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GeneralAid generalAid = db.GeneralAid.Find(id);
            db.GeneralAid.Remove(generalAid);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/GeneralAids/Create.cshtml
@model Gam3iaWeb.GeneralAid

@{
    ViewBag.Title = "تسليم مساعده عامه";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>تسليم مساعده عامه</h2>
<div class="float_left">
    @Html.ActionLink("عودة إلي القائمة", "Index")
</div>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PoorID, "اسم الحاله", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.DropDownList("PoorID", null, htmlAttributes: new { @class = "selectpicker show-tick form-control",@data_live_search=true })
                @Html.ValidationMessageFor(model => model.PoorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceID, "نوع المساعده", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.DropDownList("ServiceID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ReceiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.ReceiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReceiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>
     

        

      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5 col-md-offset-1">
                <input type="submit" value="إنشاء" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/GeneralAids/Delete.cshtml
@model Gam3iaWeb.GeneralAid

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>حذف</h2>

<h3>هل أنت واثق من حذف هذا العنصر؟</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PoorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Poor.PoorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Service.ServiceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceiveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.VolunteerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.UserName)
        </dd>*@

        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-default" /> |
            @Html.ActionLink("عودة إلي القائمة", "Index")
        </div>
    }
</div>

Views/GeneralAids/Details.cshtml
@model Gam3iaWeb.GeneralAid

@{
    ViewBag.Title = "تفاصيل المساعده";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>تفاصيل المساعده</h2>
<p class="float_left">
    @Html.ActionLink("تعديل", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("عوده إلي القائمة", "Index")
</p>
<div>
    <hr />
    <div class="form-horizontal disabledform">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PoorID, "اسم الحاله", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Poor.PoorName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ServiceID, "نوع الخدمة", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Service.ServiceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            @Html.LabelFor(model => model.ReceiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.ReceiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReceiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>
       
        
    </div>
</div>

Views/GeneralAids/Edit.cshtml
@model Gam3iaWeb.GeneralAid

@{
    ViewBag.Title = "تعديل";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>تعديل</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="float_left">
            @Html.ActionLink("عودة إلي القائمة", "Index")
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PoorID, "اسم الحاله", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.DropDownList("PoorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PoorID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ServiceID, "نوع الخدمة", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.DropDownList("ServiceID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        

      

        <div class="form-group">
            @Html.LabelFor(model => model.ReceiveDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.ReceiveDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReceiveDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5 col-md-offset-1">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
        @Html.LabelFor(model => model.VolunteerID, "مدخل البيانات", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-5 col-md-offset-1">
            @Html.DropDownList("VolunteerID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VolunteerID, "", new { @class = "text-danger" })
        </div>
    </div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-5 col-md-offset-1">
                <input type="submit" value="حفظ" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/GeneralAids/Index.cshtml
@model IEnumerable<Gam3iaWeb.GeneralAid>

@{
    ViewBag.Title = "قائمة المساعدات";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>قائمة المساعدات</h2>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        @Html.ActionLink("مساعده لحاله جديده", "CreateNew", "GeneralAids", null, new { @class = "btn btn-default", @role = "button" })
    </div>
    <div class="col-md-4"> @Html.ActionLink("مساعدة لحاله سابقه", "Create", "GeneralAids", null, new { @class = "btn btn-default", @role = "button" })</div>

</div>
<br />
@*@Html.DropDownList("Services", new SelectList(ViewBag.ServicesList), "-- حدد نوع المساعده --", new { @class = "form-control" })*@
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        @using (Html.BeginForm("Index", "GeneralAids", FormMethod.Get))
        {
            @Html.Label("اختر نوع المساعده")
            @Html.DropDownList("ServicesList", null, htmlAttributes: new { @class = "form-control" })
        }
        </div>
    </div>
        <br />

        <table class="table table-condensed datatable4">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ServiceID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PoorID)
                    </th>

                    <th>
                            @Html.DisplayNameFor(model => model.CityName)
                        </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ReceiveDate)
                    </th>
                    <th>
                            @Html.DisplayNameFor(model => model.Tag)
                        </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.VolunteerID)
                        </th>*@

                    <th></th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Service.ServiceName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Poor.PoorName)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.CityName)
                    </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReceiveDate)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Tag)
                    </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.AspNetUsers.UserName)
                    </td>*@


                <td>
                    @Html.ActionLink("تعديل", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("التفاصيل", "Details", new { id = item.ID }) |
                    @Html.ActionLink("حذف", "Delete", new { id = item.ID })
                </td>
            </tr>
            }

        </table>