Models/CaseStudyViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Gam3iaWeb.Models
{

    public class CaseStudyViewModel
    {
        Gam3iaEntities context = new Gam3iaEntities();
        [Key]
        public int CaseID { get; set; }
        [Display(Name = "اسم القريه")]
        public string VillageName { get; set; }
        [Display(Name = "اسم الدليل ")]
        public string ReporterName { get; set; }
        [Display(Name = "تليفون الدليل")]
        public string ReporterPhone { get; set; }
        [Display(Name = "تصنيف الأسرة")]
        public IEnumerable<SelectListItem> FamilyClasses
        {
            set
            {

            }
            get
            {
               return  Enum.GetValues(typeof(FamilyClassEnum))
                .Cast<FamilyClassEnum>()
                .Select(p => new SelectListItem()
                {
                    Text = p.ToString(),
                    Value = ((int)p).ToString()
                })
                .ToList();
                
            }
        }
                
          
        [Display(Name = "تصنيف الأسرة")]
        public string FamilyClass { get ; set; }
       
        [Display(Name = "الاسم رباعي  ")]
        public string PoorName { get; set; }
       
        [Display(Name = "رقم البطاقه ")]
        public string PoorNID { get; set; }
        [Display(Name = "اسم الزوج / الزوجة ")]
        public string PartnerName { get; set; }
        [Display(Name = "رقم بطاقة الزوج /الزوجة ")]
        public string PartnerNID { get; set; }
        [Required(ErrorMessage = "يجب إدخال العنوان")]
        [Display(Name = "العنوان ")]
        public string Address { get; set; }
        [Display(Name = "عائل الأسرة")]
        public IEnumerable<SelectListItem> Breadwinners
        {
            set { }
            get
            {
                return Enum.GetValues(typeof(BreadwinnerEnum))
                                                .Cast<BreadwinnerEnum>()
                                                .Select(p => new SelectListItem()
                                                {
                                                    Text = p.ToString(),
                                                    Value = ((int)p).ToString()
                                                })
                                               .ToList();
            }
        }
        [Display(Name = "عائل الأسرة")]
        public string Breadwinner { get; set; }
        [Display(Name = "الوظيفة ")]
        public string Job { get; set; }
        //Html.DropDownListFor(m => m.CityId, Model.cities)
        [Display(Name = "الحاله التعليميه ")]

        public IEnumerable<SelectListItem> EducationStates {
            set { }
            get {
                return Enum.GetValues(typeof(EducationStateEnum))
                                .Cast<EducationStateEnum>()
                                .Select(p => new SelectListItem()
                                {
                                    Text = p.ToString(),
                                    Value = ((int)p).ToString()
                                })
                               .ToList();
            }  }

        [Display(Name = "الحاله التعليميه ")]
        public string EducationState { get; set; }
        [Display(Name = "عدد الأبناء ")]
        public Nullable<int> ChildrenNo { get; set; }
        [Display(Name = "عدد الأبناء في التعليم ")]
        public Nullable<int> ChildrenInEducationNo { get; set; }
        [Display(Name = "عدد الأبناء المتزوجين أو المسافرين ")]
        public Nullable<int> TravelledOrMarriedChildrenNo { get; set; }
        [Required]
        [Display(Name = "التليفون 1 ")]
        public string Telephone1 { get; set; }
        [Display(Name = "التليفون 2 ")]
        public string Telephone2 { get; set; }
        [Display(Name = "المطلوب ")]
        public string Target { get; set; }
        [Display(Name = "رأي الباحث ")]
        public string ReviewerOpinion { get; set; }
        [Display(Name = "المتطوع ")]
        public string VolunteerName { get; set; }
       
        [Display(Name = "أدخل بواسطة المتطوع ")]
        public string VolunteerID { get; set; }
        [Display(Name = "اختر اسم المحتاج   ")]

        List<SelectListItem> Poors { get; set; }
        [Display(Name = "اختر اسم المحتاج ")]
        public int PoorID { get; set; }

        [Display(Name = "مياه ")]

        public Nullable<int> WaterFees { get; set; }
        [Display(Name = "كهرباء ")]
        public Nullable<int> ElectricityFees { get; set; }
        [Display(Name = "أقساط ")]
        public Nullable<int> InstallmentsFees { get; set; }
        [Display(Name = "علاج ")]
        public Nullable<int> DrugsFees { get; set; }
        [Display(Name = "إيجار ")]
        public Nullable<int> RentFees { get; set; }
        [Display(Name = "مصروفات أخري ")]
        public Nullable<int> OtherFees { get; set; }
        [Display(Name = "راتب شهري ")]
        public Nullable<int> MonthlySalary { get; set; }
        [Display(Name = "يوميه ")]
        public Nullable<int> DailySalary { get; set; }
        [Display(Name = "تأمينات ")]
        public Nullable<int> InsuranceIncome { get; set; }
        [Display(Name = "جمعيات ")]
        public Nullable<int> SocitiesIncome { get; set; }
        [Display(Name = "معاش ")]
        public Nullable<int> MaashIncome { get; set; }
        [Display(Name = "دخل آخر ")]
        public Nullable<int> OtherIncome { get; set; }
        [Display(Name = "أراضي  ")]
        public string LandsOwned { get; set; }
        [Display(Name = "أغنام / ماشيه ")]
        public string AnimalsOwned { get; set; }
        [Display(Name = "طيور ")]
        public string BirdsOwned { get; set; }
        [Display(Name = "ممتلكات أخري ")]
        public string OtherOwned { get; set; }
        [Display(Name = "أجهزة ")]
        public string DevicesOwned { get; set; }
        [Display(Name = "عدد الغرف ")]
        public Nullable<int> RoomsNo { get; set; }
        [Display(Name = "نوع المسكن ")]
        public IEnumerable<SelectListItem> HouseTypes {
            set { }
            get
            {
                return Enum.GetValues(typeof(HouseTypeEnum))
                                               .Cast<HouseTypeEnum>()
                                               .Select(p => new SelectListItem()
                                               {
                                                   Text = p.ToString(),
                                                   Value = ((int)p).ToString()
                                               })
                                              .ToList();
            }
        }
        [Display(Name = "نوع المسكن ")]
        public string HouseType { get; set; }
        [Display(Name = "نوع الحوائط ")]
        public IEnumerable<SelectListItem> WallTypes
        {
            set { }
            get
            {
                return Enum.GetValues(typeof(WallTypeEnum))
                                .Cast<WallTypeEnum>()
                                .Select(p => new SelectListItem()
                                {
                                    Text = p.ToString(),
                                    Value = ((int)p).ToString()
                                })
                               .ToList();
            }
        }
        [Display(Name = "نوع الحوائط ")]
        public string WallsType { get; set; }
        [Display(Name = "نوع السقف ")]
        public IEnumerable<SelectListItem> RoofTypes { set { }
        get
            {
                return Enum.GetValues(typeof(RoofTypeEnum))
                                .Cast<RoofTypeEnum>()
                                .Select(p => new SelectListItem()
                                {
                                    Text = p.ToString(),
                                    Value = ((int)p).ToString()
                                })
                               .ToList();
            }
        }
        [Display(Name = "نوع السقف ")]
        public string RoofType { get; set; }
        [Display(Name = "الأرضيه ")]
        public string Floor { get; set; }
        [Display(Name = "عداد مياه ")]
        public bool HasWaterLine { get; set; }
        [Display(Name = "عداد كهرباء ")]
        public bool HasElectLine { get; set; }
        [Display(Name = "صرف صحي ")]
        public bool HasSarfLine { get; set; }
        [Display(Name = "أخرى ")]
        public string OtherLines { get; set; }
        [Display(Name = "تعليقات أخري عن الحاله ")]
        public string Comments { get; set; }
        [Display(Name = "تاريخ البحث ")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ResearchDate { get; set; }
        [Display(Name = "اسم الباحث ")]
        public string ReviewerName { get; set; }
        //public int MyProperty { get; set; }
        [Display(Name = "مستحق؟ ")]
        
        public bool IsDeserved { get; set; }
        [Display(Name = "مستحق؟ ")]

        public string IsDeservedS {
            get
            {
                if (IsDeserved == true) return "نعم";
                else return "لا";
            }
        }


        public static implicit operator CaseStudyViewModel(CaseStudy caseStudy)
        {
            Gam3iaEntities db = new Gam3iaEntities();

            CaseStudy study = (from ss in db.CaseStudy.Include("AspNetUsers")
                               where ss.CaseID == caseStudy.CaseID
                               select ss).FirstOrDefault();
            Poor poor = (from p in db.Poor where p.ID == caseStudy.PoorID select p).FirstOrDefault();

            return new CaseStudyViewModel
            {
                CaseID = study.CaseID,
                VillageName = study.VillageName,
                Address = study.Address,

Controllers/CaseStudiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gam3iaWeb;
using Gam3iaWeb.Models;

namespace Gam3iaWeb.Controllers
{
    [Authorize]
    public class CaseStudiesController : Controller
    {
        private Gam3iaEntities db = new Gam3iaEntities();

        // GET: CaseStudies
        public ActionResult Index()
        {
            List<CaseStudy> caseStudylst = db.CaseStudy.Include(c => c.AspNetUsers).ToList();
            List<CaseStudyViewModel> vms = new List<CaseStudyViewModel>();
            foreach (var item in caseStudylst)
            {
                vms.Add((CaseStudyViewModel)item);
            }
            return View(vms);
        }

        public ActionResult test()
        {
            return View("test");
        }

        // GET: CaseStudies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CaseStudy caseStudy = db.CaseStudy.Find(id);
            CaseStudyViewModel vm = caseStudy;
            if (caseStudy == null)
            {
                return HttpNotFound();
            }
            return View(vm);
        }

        // GET: CaseStudies/Create
        public ActionResult Create()
        {
            CaseStudyViewModel vm = new CaseStudyViewModel();
            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName");
            ViewBag.Poors = new SelectList(db.Poor, "ID", "PoorName");

            return View(vm);
        }

        // POST: CaseStudies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CaseID,VillageName,ReporterName,ReporterPhone,FamilyClass,PartnerName,PartnerNID,Address,Breadwinner,Job,EducationState,ChildrenNo,ChildrenInEducationNo,TravelledOrMarriedChildrenNo,Telephone1,Telephone2,Target,ReviewerOpinion,VolunteerID,WaterFees,ElectricityFees,InstallmentsFees,DrugsFees,RentFees,OtherFees,MonthlySalary,DailySalary,InsuranceIncome,SocitiesIncome,MaashIncome,OtherIncome,LandsOwned,AnimalsOwned,BirdsOwned,OtherOwned,DevicesOwned,RoomsNo,HouseType,WallsType,RoofType,Floor,HasWaterLine,HasElectLine,HasSarfLine,OtherLines,Comments,PoorID,ReviewerName,ResearchDate,IsDeserved")] CaseStudyViewModel caseStudyvm)
        {

            CaseStudy caseStudy = (CaseStudy)caseStudyvm;
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                db.CaseStudy.Add(caseStudy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName", caseStudy.VolunteerID);
            return View((CaseStudyViewModel)caseStudy);
        }

        // GET: CaseStudies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CaseStudy caseStudy = db.CaseStudy.Find(id);
           
            if (caseStudy == null)
            {
                return HttpNotFound();
            }
            ViewBag.Poors = new SelectList(db.Poor, "ID", "PoorName");
            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName", caseStudy.VolunteerID);
            return View((CaseStudyViewModel)caseStudy);
        }

        // POST: CaseStudies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CaseID,VillageName,ReporterName,ReporterPhone,FamilyClass,PartnerName,PartnerNID,Address,Breadwinner,Job,EducationState,ChildrenNo,ChildrenInEducationNo,TravelledOrMarriedChildrenNo,Telephone1,Telephone2,Target,ReviewerOpinion,VolunteerID,WaterFees,ElectricityFees,InstallmentsFees,DrugsFees,RentFees,OtherFees,MonthlySalary,DailySalary,InsuranceIncome,SocitiesIncome,MaashIncome,OtherIncome,LandsOwned,AnimalsOwned,BirdsOwned,OtherOwned,DevicesOwned,RoomsNo,HouseType,WallsType,RoofType,Floor,HasWaterLine,HasElectLine,HasSarfLine,OtherLines,Comments,PoorID,ReviewerName,ResearchDate,IsDeserved")] CaseStudyViewModel caseStudyvm)
        {
            CaseStudy caseStudy = (CaseStudy)caseStudyvm;
            if (ModelState.IsValid)
            {
                db.Entry(caseStudy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName", caseStudy.VolunteerID);
            return View((CaseStudyViewModel)caseStudy);
        }

        // GET: CaseStudies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CaseStudy caseStudy = db.CaseStudy.Find(id);
            if (caseStudy == null)
            {
                return HttpNotFound();
            }
            return View((CaseStudyViewModel)caseStudy);
        }

        // POST: CaseStudies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CaseStudy caseStudy = db.CaseStudy.Find(id);
            db.CaseStudy.Remove(caseStudy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult CreateNew()
        {
            //ViewBag.VolunteerID = new SelectList(db.AspNetUsers, "Id", "UserName");
            //return View();
            Session["caller"] = "CaseStudy";
            return RedirectToAction("Create", "Poors");
        }

        
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/CaseStudies/Delete.cshtml
@model Gam3iaWeb.Models.CaseStudyViewModel

@{
    ViewBag.Title = "حذف";
}

<h2>حذف</h2>

<h3>هل أنت واثق من حذف هذا العنصر؟</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PoorName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PoorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VillageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VillageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReporterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReporterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReporterPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReporterPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FamilyClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FamilyClass)
        </dd>

        
    </dl>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-default" /> |
            @Html.ActionLink("عودة إلي القائمة", "Index")
        </div>
    }
</div>

Views/CaseStudies/Index.cshtml
@model IEnumerable<Gam3iaWeb.Models.CaseStudyViewModel>

@{
    ViewBag.Title = "بحث الحالات";
}
<div class="container">
    <h2>بحث الحالات</h2>
    <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-3">
             @Html.ActionLink("إضافة بحث لحاله جديده", "CreateNew", "CaseStudies", null, new { @class = "btn btn-default" ,@role= "button" }  )
         </div>
        <div class="col-md-3"> @Html.ActionLink(" إضافة بحث لحاله سابقة", "Create", "CaseStudies", null,new {  @class = "btn btn-default", @role = "button" } )</div>

    </div>
    <br />
    <table class="table table-hover table-striped datatable" id="cases">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.VillageName)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.ReporterName)
                </th>*@
                @*<th>
                    @Html.DisplayNameFor(model => model.ReporterPhone)
                </th>*@
                @*<th>
                    @Html.DisplayNameFor(model => model.FamilyClass)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.PoorName)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.PoorNID)
                </th>*@
                @*<th>
                    @Html.DisplayNameFor(model => model.PartnerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PartnerNID)
                </th>*@
                @*<th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Breadwinner)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Job)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.EducationState)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.ResearchDate)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.ChildrenInEducationNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TravelledOrMarriedChildrenNo)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Telephone1)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Telephone2)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Target)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsDeservedS)
                </th>
                
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.VillageName)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.ReporterName)
                </td>*@
                @*<td>
                        @Html.DisplayFor(modelItem => item.ReporterPhone)
                    </td>*@
                @*<td>
                    @Html.DisplayFor(modelItem => item.FamilyClass)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.PoorName)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.PoorNID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PartnerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PartnerNID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Breadwinner)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Job)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.EducationState)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.ResearchDate)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.ChildrenInEducationNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TravelledOrMarriedChildrenNo)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Telephone1)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Telephone2)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Target)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.ReviewerOpinion)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.IsDeservedS)
                </td>
                <td>
                    @Html.ActionLink("تعديل", "Edit", new { id = item.CaseID }) |
                    @Html.ActionLink("التفاصيل", "Details", new { id = item.CaseID }) |
                    @Html.ActionLink("مسح", "Delete", new { id = item.CaseID })
                </td>
            </tr>
        }

    </table>
</div>

Views/CaseStudies/test.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/bootstrap-select.css">
    

    <style>
        body {
            padding-top: 70px;
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="/js/lib/bootstrap-select.js"></script>
    @*<link href="/css/jquery.dataTables.css" rel="stylesheet" />
    <link href="/css/dataTables.bootstrap.css" rel="stylesheet" />

    <link href="~/css/bootstrap-select.css" rel="stylesheet" />*@
    <link rel="stylesheet" type="text/css" href="//www.fontstatic.com/f=droid-sans" />

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Hope Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />

</head>
<body>
    <div> 
        <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
            <option>بقره</option>
            <option>كره</option>
            <option class="get-class" disabled>كلب</option>
            <!--<optgroup label="test" data-subtext="optgroup subtext">-->
            <option>موز</option>
            <option selected>اسد</option>
            <option>مصر</option>
            <!--</optgroup>-->
        </select>
    </div>
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datatables")


    <script src="~/js/lib/jquery.dataTables.js"></script>
    <script src="~/js/lib/dataTables.bootstrap.js"></script>
    <script src="~/js/lib/bootstrap-select.js"></script>

   
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
*@
</body>
</html>